"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Papyrus.py']
DATA_FILES = ['/Users/zmichaelov/Projects/papyrus/assets']
OPTIONS = {'arch': 'i386', 'argv_emulation': True}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
